(() => {
  let token = ''; const out = (id, value) => { const el = document.getElementById(id); if (el) el.textContent = typeof value === 'string' ? value : JSON.stringify(value, null, 2); };
  fetch('/api/csrf').then(r => r.json()).then(v => { token = v.token; sessionStorage.setItem('house-csrf', token); }).catch(e => out('status', `unhealthy: ${e.message}`));
  fetch('/api/health').then(async r => { const v = await r.json(); if (!r.ok) throw new Error(v.error || `HTTP ${r.status}`); out('status', `ready: ${v.status}`); }).catch(e => out('status', `unhealthy: ${e.message}`));
  fetch('/api/backups').then(r => r.json()).then(v => out('backup-results', v)).catch(e => out('backup-results', e.message));
  async function post(path, payload) { const r = await fetch(path, { method: 'POST', headers: {'content-type':'application/json','x-csrf-token':token}, body: JSON.stringify(payload) }); const data = await r.json().catch(() => ({error:'invalid response'})); if (!r.ok) throw new Error(data.error || `HTTP ${r.status}`); return data; }
  async function rpc(form) { const p = {}; for (const el of form.elements) if (el.name && (el.type !== 'checkbox' || el.checked)) p[el.name] = el.type === 'number' ? Number(el.value) : el.type === 'checkbox' ? true : el.value; const method = form.dataset.method; const result = await post('/api/rpc', {method, params:p}); out(method === 'recall' ? 'recall-results' : method === 'anamnesis' ? 'anamnesis-results' : 'status', result); }
  document.querySelectorAll('form[data-method]').forEach(f => f.addEventListener('submit', async e => { e.preventDefault(); try { await rpc(f); } catch (x) { out('status', x.message); } }));
  document.getElementById('restore').addEventListener('submit', async e => { e.preventDefault(); const p = Object.fromEntries(new FormData(e.currentTarget)); if (!confirm('Restore will replace the target database. Continue?')) return; try { out('backup-results', await post('/api/restore', p)); } catch (x) { out('backup-results', x.message); } });
  document.getElementById('backup-create').addEventListener('click', async () => { try { out('backup-results', await post('/api/backup', {})); } catch (x) { out('backup-results', x.message); } });
  for (const [id, operation] of [['cluster-check','check'],['cluster-dry','rebuild'],['cluster-rebuild','rebuild']]) document.getElementById(id).addEventListener('click', async () => { const dryRun = id === 'cluster-dry'; if (!dryRun && operation === 'rebuild' && !confirm('Rebuild cluster?')) return; try { out('cluster-results', await post('/api/rpc', {method:'cluster_maintenance', params:{room:'tuner', operation, ...(dryRun ? {dryRun:true} : {}), ...(operation === 'rebuild' ? {confirm:'REBUILD'} : {})}})); } catch (x) { out('cluster-results', x.message); } });
})();